In [2]:
import pandas as pd
from datetime import datetime
# Đọc file Parquet
df = pd.read_parquet('/home/tung/Downloads/DE_K3_M2/project/data/pump/yellow_tripdata_2024-01.parquet', engine='pyarrow')

# Hiển thị dữ liệu
print(df.head())

   VendorID tpep_pickup_datetime tpep_dropoff_datetime  passenger_count  \
0         2  2024-01-01 00:57:55   2024-01-01 01:17:43              1.0
1         1  2024-01-01 00:03:00   2024-01-01 00:09:36              1.0
2         1  2024-01-01 00:17:06   2024-01-01 00:35:01              1.0
3         1  2024-01-01 00:36:38   2024-01-01 00:44:56              1.0
4         1  2024-01-01 00:46:51   2024-01-01 00:52:57              1.0

   trip_distance  RatecodeID store_and_fwd_flag  PULocationID  DOLocationID  \
0           1.72         1.0                  N           186            79
1           1.80         1.0                  N           140           236
2           4.70         1.0                  N           236            79
3           1.40         1.0                  N            79           211
4           0.80         1.0                  N           211           148

   payment_type  fare_amount  extra  mta_tax  tip_amount  tolls_amount  \
0             2         17.7    1.0      0.5        0.00           0.0
1             1         10.0    3.5      0.5        3.75           0.0
2             1         23.3    3.5      0.5        3.00           0.0
3             1         10.0    3.5      0.5        2.00           0.0
4             1          7.9    3.5      0.5        3.20           0.0

   improvement_surcharge  total_amount  congestion_surcharge  Airport_fee
0                    1.0         22.70                   2.5          0.0
1                    1.0         18.75                   2.5          0.0
2                    1.0         31.30                   2.5          0.0
3                    1.0         17.00                   2.5          0.0
4                    1.0         16.10                   2.5          0.0

In [3]:
df.columns[[0]]

Index(['VendorID'], dtype='object')

In [4]:
df.describe()

,VendorID,tpep_pickup_datetime,tpep_dropoff_datetime,passenger_count,trip_distance,RatecodeID,PULocationID,DOLocationID,payment_type,fare_amount,extra,mta_tax,tip_amount,tolls_amount,improvement_surcharge,total_amount,congestion_surcharge,Airport_fee
count,2.964624e+06,2964624,2964624,2.824462e+06,2.964624e+06,2.824462e+06,2.964624e+06,2.964624e+06,2.964624e+06,2.964624e+06,2.964624e+06,2.964624e+06,2.964624e+06,2.964624e+06,2.964624e+06,2.964624e+06,2.824462e+06,2.824462e+06
mean,1.754204e+00,2024-01-17 00:46:36.431092,2024-01-17 01:02:13.208130,1.339281e+00,3.652169e+00,2.069359e+00,1.660179e+02,1.651167e+02,1.161271e+00,1.817506e+01,1.451598e+00,4.833823e-01,3.335870e+00,5.270212e-01,9.756319e-01,2.680150e+01,2.256122e+00,1.411611e-01
min,1.000000e+00,2002-12-31 22:59:39,2002-12-31 23:05:41,0.000000e+00,0.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00,0.000000e+00,-8.990000e+02,-7.500000e+00,-5.000000e-01,-8.000000e+01,-8.000000e+01,-1.000000e+00,-9.000000e+02,-2.500000e+00,-1.750000e+00
25%,2.000000e+00,2024-01-09 15:59:19.750000,2024-01-09 16:16:23,1.000000e+00,1.000000e+00,1.000000e+00,1.320000e+02,1.140000e+02,1.000000e+00,8.600000e+00,0.000000e+00,5.000000e-01,1.000000e+00,0.000000e+00,1.000000e+00,1.538000e+01,2.500000e+00,0.000000e+00
50%,2.000000e+00,2024-01-17 10:45:37.500000,2024-01-17 11:03:51.500000,1.000000e+00,1.680000e+00,1.000000e+00,1.620000e+02,1.620000e+02,1.000000e+00,1.280000e+01,1.000000e+00,5.000000e-01,2.700000e+00,0.000000e+00,1.000000e+00,2.010000e+01,2.500000e+00,0.000000e+00
75%,2.000000e+00,2024-01-24 18:23:52.250000,2024-01-24 18:40:29,1.000000e+00,3.110000e+00,1.000000e+00,2.340000e+02,2.340000e+02,1.000000e+00,2.050000e+01,2.500000e+00,5.000000e-01,4.120000e+00,0.000000e+00,1.000000e+00,2.856000e+01,2.500000e+00,0.000000e+00
max,6.000000e+00,2024-02-01 00:01:15,2024-02-02 13:56:52,9.000000e+00,3.127223e+05,9.900000e+01,2.650000e+02,2.650000e+02,4.000000e+00,5.000000e+03,1.425000e+01,4.000000e+00,4.280000e+02,1.159200e+02,1.000000e+00,5.000000e+03,2.500000e+00,1.750000e+00
std,4.325902e-01,NaN,NaN,8.502817e-01,2.254626e+02,9.823219e+00,6.362391e+01,6.931535e+01,5.808686e-01,1.894955e+01,1.804102e+00,1.177600e-01,3.896551e+00,2.128310e+00,2.183645e-01,2.338558e+01,8.232747e-01,4.876239e-01

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2964624 entries, 0 to 2964623
Data columns (total 19 columns):
 #   Column                 Dtype
---  ------                 -----
 0   VendorID               int32
 1   tpep_pickup_datetime   datetime64[us]
 2   tpep_dropoff_datetime  datetime64[us]
 3   passenger_count        float64
 4   trip_distance          float64
 5   RatecodeID             float64
 6   store_and_fwd_flag     object
 7   PULocationID           int32
 8   DOLocationID           int32
 9   payment_type           int64
 10  fare_amount            float64
 11  extra                  float64
 12  mta_tax                float64
 13  tip_amount             float64
 14  tolls_amount           float64
 15  improvement_surcharge  float64
 16  total_amount           float64
 17  congestion_surcharge   float64
 18  Airport_fee            float64
dtypes: datetime64[us](2), float64(12), int32(3), int64(1), object(1)
memory usage: 395.8+ MB

In [6]:
row = df.sample()
##convert to list
feature_values = row.values.tolist()[0]

feature_values[1] = str(feature_values[1])
feature_values[2] = str(feature_values[2])
created_time = str(datetime.now().strftime("%Y-%m-%d %H:%M:%S"))
data = [created_time] + feature_values

In [7]:
import pandas as pd
import os
from datetime import datetime
# Loop through Parquet files in nyc_taxi_data directory
for filename in os.listdir("/home/tung/Downloads/DE_K3_M2/nyc_taxi_data")[2:3]:
    if filename.endswith(".parquet"):
        filepath = os.path.join("/home/tung/Downloads/DE_K3_M2/nyc_taxi_data", filename)

        # Read Parquet data
        data = pd.read_parquet(filepath)
        # print(table)
        # print(data)
        current_datetime = current_datetime = datetime.now()
        data.insert(loc=0, column='created', value=current_datetime)
        print(data)
        print(filename)

In [8]:
data = data.fillna('NULL')
data

AttributeError: 'list' object has no attribute 'fillna'

In [15]:
data.columns

Index(['created', 'VendorID', 'tpep_pickup_datetime', 'tpep_dropoff_datetime',
       'passenger_count', 'trip_distance', 'RatecodeID', 'store_and_fwd_flag',
       'PULocationID', 'DOLocationID', 'payment_type', 'fare_amount', 'extra',
       'mta_tax', 'tip_amount', 'tolls_amount', 'improvement_surcharge',
       'total_amount', 'congestion_surcharge', 'airport_fee'],
      dtype='object')

In [8]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 12442394 entries, 0 to 12442393
Data columns (total 20 columns):
 #   Column                 Dtype
---  ------                 -----
 0   created                datetime64[us]
 1   VendorID               int64
 2   tpep_pickup_datetime   object
 3   tpep_dropoff_datetime  object
 4   passenger_count        int64
 5   trip_distance          float64
 6   RatecodeID             int64
 7   store_and_fwd_flag     object
 8   PULocationID           int64
 9   DOLocationID           int64
 10  payment_type           int64
 11  fare_amount            float64
 12  extra                  float64
 13  mta_tax                float64
 14  tip_amount             float64
 15  tolls_amount           float64
 16  improvement_surcharge  float64
 17  total_amount           float64
 18  congestion_surcharge   object
 19  airport_fee            object
dtypes: datetime64[us](1), float64(8), int64(6), object(5)
memory usage: 1.9+ GB

In [11]:
len(data.columns)

20

In [9]:
import os
os.listdir("/home/tung/Downloads/DE_K3_M2/nyc_taxi_data")

['yellow_tripdata_2015-02.parquet',
 'yellow_tripdata_2024-05.parquet',
 'yellow_tripdata_2020-04.parquet',
 'green_tripdata_2016-11.parquet',
 'green_tripdata_2018-04.parquet',
 'green_tripdata_2021-04.parquet',
 'yellow_tripdata_2022-04.parquet',
 'yellow_tripdata_2016-10.parquet',
 'yellow_tripdata_2017-08.parquet',
 'yellow_tripdata_2016-12.parquet',
 'green_tripdata_2017-10.parquet',
 'green_tripdata_2018-08.parquet',
 'yellow_tripdata_2022-10.parquet',
 'green_tripdata_2017-03.parquet',
 'green_tripdata_2023-06.parquet',
 'yellow_tripdata_2015-08.parquet',
 'yellow_tripdata_2017-05.parquet',
 'green_tripdata_2016-12.parquet',
 'green_tripdata_2018-09.parquet',
 'green_tripdata_2017-07.parquet',
 'yellow_tripdata_2018-01.parquet',
 'yellow_tripdata_2021-04.parquet',
 'green_tripdata_2020-01.parquet',
 'green_tripdata_2020-04.parquet',
 'green_tripdata_2018-02.parquet',
 'green_tripdata_2023-01.parquet',
 'green_tripdata_2017-09.parquet',
 'green_tripdata_2021-07.parquet',
 'yellow_tripdata_2024-04.parquet',
 'green_tripdata_2019-09.parquet',
 'yellow_tripdata_2022-01.parquet',
 'green_tripdata_2023-05.parquet',
 'yellow_tripdata_2023-08.parquet',
 'green_tripdata_2018-07.parquet',
 'green_tripdata_2021-11.parquet',
 'green_tripdata_2017-05.parquet',
 'green_tripdata_2023-02.parquet',
 'yellow_tripdata_2017-06.parquet',
 'green_tripdata_2016-03.parquet',
 'yellow_tripdata_2021-01.parquet',
 'yellow_tripdata_2016-02.parquet',
 'green_tripdata_2015-11.parquet',
 'yellow_tripdata_2015-05.parquet',
 'green_tripdata_2020-07.parquet',
 'green_tripdata_2021-02.parquet',
 'yellow_tripdata_2018-09.parquet',
 'yellow_tripdata_2017-07.parquet',
 'green_tripdata_2023-07.parquet',
 'yellow_tripdata_2024-03.parquet',
 'yellow_tripdata_2018-06.parquet',
 'green_tripdata_2017-11.parquet',
 'yellow_tripdata_2016-03.parquet',
 'green_tripdata_2017-04.parquet',
 'green_tripdata_2022-04.parquet',
 'green_tripdata_2017-08.parquet',
 'yellow_tripdata_2016-01.parquet',
 'green_tripdata_2016-08.parquet',
 'green_tripdata_2022-12.parquet',
 'yellow_tripdata_2019-12.parquet',
 'yellow_tripdata_2023-02.parquet',
 'green_tripdata_2024-05.parquet',
 'yellow_tripdata_2015-01.parquet',
 'green_tripdata_2022-01.parquet',
 'green_tripdata_2024-03.parquet',
 'green_tripdata_2024-06.parquet',
 'green_tripdata_2021-08.parquet',
 'yellow_tripdata_2019-06.parquet',
 'green_tripdata_2022-05.parquet',
 'green_tripdata_2022-06.parquet',
 'yellow_tripdata_2019-09.parquet',
 'yellow_tripdata_2021-09.parquet',
 'yellow_tripdata_2020-10.parquet',
 'yellow_tripdata_2023-09.parquet',
 'green_tripdata_2023-09.parquet',
 'yellow_tripdata_2016-11.parquet',
 'yellow_tripdata_2022-08.parquet',
 'green_tripdata_2015-05.parquet',
 'yellow_tripdata_2019-04.parquet',
 'green_tripdata_2019-08.parquet',
 'yellow_tripdata_2016-06.parquet',
 'yellow_tripdata_2016-08.parquet',
 'green_tripdata_2015-09.parquet',
 'green_tripdata_2016-09.parquet',
 'yellow_tripdata_2018-03.parquet',
 'yellow_tripdata_2019-01.parquet',
 'yellow_tripdata_2020-11.parquet',
 'green_tripdata_2019-07.parquet',
 'yellow_tripdata_2020-01.parquet',
 'green_tripdata_2018-01.parquet',
 'yellow_tripdata_2017-04.parquet',
 'green_tripdata_2016-02.parquet',
 'yellow_tripdata_2021-11.parquet',
 'yellow_tripdata_2022-12.parquet',
 'yellow_tripdata_2022-02.parquet',
 'green_tripdata_2016-07.parquet',
 'yellow_tripdata_2019-07.parquet',
 'yellow_tripdata_2023-10.parquet',
 'green_tripdata_2020-05.parquet',
 'yellow_tripdata_2020-07.parquet',
 'green_tripdata_2016-05.parquet',
 'green_tripdata_2022-09.parquet',
 'green_tripdata_2024-07.parquet',
 'green_tripdata_2015-10.parquet',
 'yellow_tripdata_2016-05.parquet',
 'yellow_tripdata_2015-10.parquet',
 'green_tripdata_2017-01.parquet',
 'green_tripdata_2019-12.parquet',
 'yellow_tripdata_2023-06.parquet',
 'yellow_tripdata_2023-07.parquet',
 'yellow_tripdata_2021-07.parquet',
 'yellow_tripdata_2017-01.parquet',
 'green_tripdata_2018-05.parquet',
 'yellow_tripdata_2020-05.parquet',
 'green_tripdata_2022-10.parquet',
 'yellow_tripdata_2023-05.parquet',
 'green_tripdata_2016-04.parquet',
 'green_tripdata_2021-05.parquet',
 'green_tripdata_2016-10.parquet',
 'green_tripdata_2019-05.parquet',
 'green_tripdata_2015-07.parquet',
 'yellow_tripdata_2022-07.parquet',
 'yellow_tripdata_2022-05.parquet',
 'yellow_tripdata_2019-03.parquet',
 'green_tripdata_2022-03.parquet',
 'green_tripdata_2016-06.parquet',
 'green_tripdata_2020-06.parquet',
 'green_tripdata_2022-02.parquet',
 'yellow_tripdata_2020-02.parquet',
 'green_tripdata_2020-03.parquet',
 'green_tripdata_2019-06.parquet',
 'yellow_tripdata_2017-11.parquet',
 'green_tripdata_2023-11.parquet',
 'yellow_tripdata_2022-06.parquet',
 'green_tripdata_2019-03.parquet',
 'green_tripdata_2022-07.parquet',
 'green_tripdata_2015-06.parquet',
 'yellow_tripdata_2023-01.parquet',
 'green_tripdata_2021-03.parquet',
 'yellow_tripdata_2018-10.parquet',
 'yellow_tripdata_2024-07.parquet',
 'green_tripdata_2019-10.parquet',
 'yellow_tripdata_2015-11.parquet',
 'green_tripdata_2021-01.parquet',
 'yellow_tripdata_2018-07.parquet',
 'yellow_tripdata_2019-10.parquet',
 'yellow_tripdata_2018-08.parquet',
 'yellow_tripdata_2015-07.parquet',
 'green_tripdata_2020-08.parquet',
 'green_tripdata_2020-12.parquet',
 'green_tripdata_2018-10.parquet',
 'green_tripdata_2023-12.parquet',
 'yellow_tripdata_2019-02.parquet',
 'green_tripdata_2021-09.parquet',
 'green_tripdata_2023-04.parquet',
 'yellow_tripdata_2023-03.parquet',
 'yellow_tripdata_2021-12.parquet',
 'green_tripdata_2019-02.parquet',
 'green_tripdata_2019-01.parquet',
 'yellow_tripdata_2023-11.parquet',
 'yellow_tripdata_2021-08.parquet',
 'yellow_tripdata_2017-03.parquet',
 'yellow_tripdata_2019-08.parquet',
 'green_tripdata_2018-11.parquet',
 'green_tripdata_2018-03.parquet',
 'green_tripdata_2021-10.parquet',
 'yellow_tripdata_2022-11.parquet',
 'green_tripdata_2015-12.parquet',
 'green_tripdata_2016-01.parquet',
 'yellow_tripdata_2015-09.parquet',
 'yellow_tripdata_2015-12.parquet',
 'green_tripdata_2019-11.parquet',
 'yellow_tripdata_2016-09.parquet',
 'green_tripdata_2023-03.parquet',
 'green_tripdata_2015-04.parquet',
 'yellow_tripdata_2024-01.parquet',
 'green_tripdata_2021-06.parquet',
 'yellow_tripdata_2015-06.parquet',
 'green_tripdata_2021-12.parquet',
 'green_tripdata_2020-10.parquet',
 'yellow_tripdata_2018-02.parquet',
 'green_tripdata_2015-08.parquet',
 'green_tripdata_2024-02.parquet',
 'green_tripdata_2020-11.parquet',
 'green_tripdata_2022-08.parquet',
 'yellow_tripdata_2018-11.parquet',
 'green_tripdata_2023-08.parquet',
 'green_tripdata_2015-01.parquet',
 'yellow_tripdata_2017-09.parquet',
 'yellow_tripdata_2016-04.parquet',
 'yellow_tripdata_2020-06.parquet',
 'green_tripdata_2018-06.parquet',
 'yellow_tripdata_2018-04.parquet',
 'yellow_tripdata_2024-02.parquet',
 'yellow_tripdata_2021-02.parquet',
 'yellow_tripdata_2018-05.parquet',
 'yellow_tripdata_2015-04.parquet',
 'yellow_tripdata_2020-03.parquet',
 'green_tripdata_2023-10.parquet',
 'yellow_tripdata_2019-11.parquet',
 'yellow_tripdata_2015-03.parquet',
 'yellow_tripdata_2021-05.parquet',
 'yellow_tripdata_2024-06.parquet',
 'yellow_tripdata_2023-12.parquet',
 'yellow_tripdata_2017-10.parquet',
 'yellow_tripdata_2023-04.parquet',
 'green_tripdata_2024-04.parquet',
 'yellow_tripdata_2019-05.parquet',
 'yellow_tripdata_2020-12.parquet',
 'yellow_tripdata_2021-10.parquet',
 'yellow_tripdata_2018-12.parquet',
 'yellow_tripdata_2016-07.parquet',
 'green_tripdata_2020-02.parquet',
 'green_tripdata_2015-02.parquet',
 'green_tripdata_2022-11.parquet',
 'green_tripdata_2015-03.parquet',
 'yellow_tripdata_2021-03.parquet',
 'green_tripdata_2018-12.parquet',
 'green_tripdata_2017-02.parquet',
 'yellow_tripdata_2021-06.parquet',
 'green_tripdata_2024-01.parquet',
 'green_tripdata_2019-04.parquet',
 'yellow_tripdata_2017-12.parquet',
 'yellow_tripdata_2017-02.parquet',
 'green_tripdata_2017-06.parquet',
 'yellow_tripdata_2022-03.parquet',
 'yellow_tripdata_2020-09.parquet',
 'green_tripdata_2017-12.parquet',
 'yellow_tripdata_2020-08.parquet',
 'green_tripdata_2020-09.parquet',
 'yellow_tripdata_2022-09.parquet']